#!/bin/bash -l
#PBS -N con_cox
#PBS -v PBS_O_SHELL=bash,PBS_ENVIRONMENT=PBS_BATCH
#PBS -r y
#PBS -q power-danielnev
#PBS -e /a/home/cc/stud_math/axelrod1/conditional_hazard_of_Cox/errors
#PBS -o /a/home/cc/stud_math/axelrod1/conditional_hazard_of_Cox/logs
#PBS -l mem=20gb,vmem=100gb,pvmem=20gb,pmem=20gb,nodes=1:ppn=10
module load R/4.1.0
Rscript /a/home/cc/stud_math/axelrod1/conditional_hazard_of_Cox/R_script/simulations_condition_cox.R $j_id
